CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affected_service VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    description TEXT,
    severity VARCHAR(255) NOT NULL,
    source_system VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT tickets_category_check CHECK (
        category IN (
            'UNCLASSIFIED',
            'ACCESS',
            'PERFORMANCE',
            'CONFIGURATION',
            'BUG',
            'INFRASTRUCTURE',
            'USER_SUPPORT',
            'SECURITY',
            'DATA_ISSUE',
            'OTHER'
        )
    ),
    CONSTRAINT tickets_severity_check CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNTRIAGED')
    ),
    CONSTRAINT tickets_status_check CHECK (
        status IN (
            'PENDING_REVIEW',
            'OPEN',
            'IN_PROGRESS',
            'WAITING',
            'RESOLVED',
            'CLOSED',
            'APPROVED',
            'REJECTED'
        )
    )
);

CREATE TABLE ai_triage_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    confidence_score DOUBLE PRECISION,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    model_name VARCHAR(255),
    probable_cause TEXT,
    raw_response TEXT,
    recommended_action TEXT,
    requires_human_review BOOLEAN,
    severity VARCHAR(255),
    summary TEXT,
    ticket_id BIGINT,
    CONSTRAINT ai_triage_results_category_check CHECK (
        category IN (
            'UNCLASSIFIED',
            'ACCESS',
            'PERFORMANCE',
            'CONFIGURATION',
            'BUG',
            'INFRASTRUCTURE',
            'USER_SUPPORT',
            'SECURITY',
            'DATA_ISSUE',
            'OTHER'
        )
    ),
    CONSTRAINT ai_triage_results_severity_check CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNTRIAGED')
    )
);

CREATE TABLE approval_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    decision VARCHAR(255),
    review_note TEXT,
    reviewer VARCHAR(255),
    ticket_id BIGINT,
    triage_result_id BIGINT,
    CONSTRAINT approval_decisions_decision_check CHECK (
        decision IN ('APPROVED', 'REJECTED', 'EDITED')
    )
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE,
    new_value TEXT,
    old_value TEXT,
    performed_by VARCHAR(255),
    ticket_id BIGINT,
    CONSTRAINT audit_logs_action_type_check CHECK (
        action_type IN (
            'TICKET_CREATED',
            'STATUS_CHANGED',
            'TRIAGE_REQUESTED',
            'AI_TRIAGE_COMPLETED',
            'AI_TRIAGE_FAILED',
            'TRIAGE_APPROVED',
            'TRIAGE_REJECTED',
            'TRIAGE_EDITED',
            'DUPLICATE_CHECKED'
        )
    )
);

CREATE TABLE duplicate_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    duplicate_of_ticket_id BIGINT NOT NULL,
    marked_by VARCHAR(255) NOT NULL,
    note TEXT,
    source_ticket_id BIGINT NOT NULL
);
