spring:
  application:
    name: opspilot-ai-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/opspilot
    username: opspilot
    password: opspilot

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080